### PR TITLE
Allow customization of CLK, MOSI & CS pin

### PR DESCRIPTION
**Pull request by xtrinch**
Can't open an issue, so will just open a PR with a piece of code that I use for my project. I needed to customize all the pins. Perhaps it could be a feature of this project.

### CODE REVIEW

**Comment by ZinggJM** [comment]
Please read CONTRIBUTING.md

**Comment by xtrinch** [comment]
I did, it says `pull requests are useful to inform users and me about interesting additions in forked repositories.` 

Was just trying to be helpful. :shrug:

**Comment by 7161457** [comment]
Hello, may I ask if GPIO18 is CLK and GPIO23 is MOSI in esp32.!How can I customize the CLK, MOSI, and pins on esp32s3 and esp32c3, as they do not have fixed spi pins

**Comment by G6EJD** [comment]
Define/set you pins then:
SPI.begin(clk, miso, miso, cs);

make sure you use the correct pins for DC and RST which can be resigned as required.

**Comment by G6EJD** [comment]
> Can't open an issue, so will just open a PR with a piece of code that I use for my project. I needed to customize all the pins. Perhaps it could be a feature of this project.

It’s so simple to reassign the SPI pins so not required

**Comment by 7161457** [comment]
Hello, may I ask how to write statements in code? I tried two methods, both of which were incorrect and unusable. It prompted a programming error

**Comment by ZinggJM** [comment]
This is not the place to ask questions.

Unfortunately PRs can't be disabled in GitHub.

So I need to unsubscribe from mail notifications, and watch no longer my repository.

**Comment by G6EJD** [comment]
> Hello, may I ask how to write statements in code? I tried two methods, both of which were incorrect and unusable. It prompted a programming error
> 
> 

You need to conduct sone self help my phone capitalised SPI should have been ‘spi’ it needs to turn red to indicate the dictionary matches. 
it’s a command not a definition and make sure you include the SPI.h library.

**Pull request closed without merging**
